spring:
  datasource:
    url: jdbc:mysql://localhost:3307/blogdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: blog
    password: blogpass

  flyway:
    enabled: true

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS"
    issuer: "blog-backend"
    access-token-minutes: 60
